import argon2 from "argon2";
import { connectDatabase, disconnectDatabase } from "../config/database.js";
import { UserModel } from "../modules/users/user.model.js";
import { UserRole } from "../modules/users/user.types.js";
import { InformationNoticeModel } from "../modules/information/information-notice.model.js";
import { GuideArticleModel } from "../modules/information/guide-article.model.js";
import { CommunityPostModel } from "../modules/community/community.model.js";
import { EventModel } from "../modules/events/event.model.js";
import { OpportunityModel } from "../modules/opportunities/opportunity.model.js";
import { AccommodationModel } from "../modules/accommodation/accommodation.model.js";
import { SafetyAlertModel } from "../modules/safety/safety-alert.model.js";
import { SafetyReportModel } from "../modules/safety/safety-report.model.js";
import { LocationModel } from "../modules/locations/location.model.js";

const D="[DEMO] ";
const future=(days:number,h=10)=>{const d=new Date();d.setDate(d.getDate()+days);d.setHours(h,0,0,0);return d};
async function upsertMany(Model:any,rows:any[],key="title"){for(const row of rows)await Model.findOneAndUpdate({[key]:row[key]},{$set:row},{upsert:true,new:true,setDefaultsOnInsert:true})}

async function run(){
 await connectDatabase();
 let admin=await UserModel.findOne({role:UserRole.ADMINISTRATOR});
 if(!admin)throw new Error("Create an administrator first with npm run seed:admin, then run npm run seed:demo");
 let student=await UserModel.findOne({role:UserRole.STUDENT});
 if(!student){student=await UserModel.create({fullName:"Demo Student",email:"demo.student@delsu-compass.local",passwordHash:await argon2.hash("DemoStudent123",{type:argon2.argon2id}),role:UserRole.STUDENT,isVerified:true,isActive:true,faculty:"Faculty of Computing",department:"Computer Science",level:400})}
 const aid=admin._id,sid=student._id,now=new Date();
 await upsertMany(InformationNoticeModel,[
  {title:D+"New student campus orientation guide",summary:"A practical checklist for getting familiar with campus before lectures become busy.",content:"Use DELSU Compass to identify important locations, confirm your timetable, review accommodation guidance and save useful campus information before your first full week.",category:"campus",audience:"public",isFeatured:true,status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Important steps before resumption",summary:"A student-friendly reminder of the things worth preparing before returning to Abraka.",content:"Confirm your academic schedule, accommodation arrangements, personal budget, transport plan and the official channels you will use for university information.",category:"academic",audience:"all",isFeatured:true,status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Examination preparation reminder",summary:"Start early by confirming venues, times and the materials permitted for each course.",content:"Use your timetable and reminders to reduce last-minute confusion. Always verify examination details through the appropriate official university source when dates or venues change.",category:"examination",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Accommodation search advisory",summary:"Inspect accommodation and confirm important details before making any payment.",content:"Check water, electricity, security, access roads, tenancy terms and the identity of the person receiving payment. DELSU Compass listings are information contributions, not payment guarantees.",category:"campus",audience:"public",isFeatured:true,status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Student safety awareness notice",summary:"Use well-lit routes at night and report useful safety information responsibly.",content:"If a situation is an emergency, contact the appropriate security or emergency service directly. DELSU Compass supports information sharing and moderation; it is not an emergency dispatch service.",category:"general",audience:"all",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Campus library usage information",summary:"Plan library visits around your study schedule and confirm current opening arrangements locally.",content:"Use the library and other study areas as part of a consistent reading routine. Details that can change should be confirmed with the responsible university unit.",category:"academic",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Course registration preparation",summary:"Prepare your course list and resolve obvious timetable clashes before completing official registration.",content:"DELSU Compass can help you organize your classes, but official course registration remains on the university-approved system.",category:"registration",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"What fresh students should know about Abraka",summary:"A short introduction to planning movement, housing, food and daily student expenses around Abraka.",content:"Learn your common routes, keep emergency contacts accessible, compare accommodation carefully and budget for transport, food, data and academic expenses.",category:"campus",audience:"public",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Student support services guide",summary:"Know where to ask for help instead of relying only on informal information.",content:"For academic, administrative, health or security concerns, identify the responsible university unit and use verified channels. Community tips are useful, but official matters should be confirmed officially.",category:"general",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Campus documentation checklist",summary:"Keep important student documents organized and accessible before you need them urgently.",content:"Store copies of the documents you frequently need for academic or administrative processes and always confirm the current requirements with the responsible university office.",category:"registration",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Transport and movement planning",summary:"Know your regular routes and leave enough time when moving between lectures and accommodation.",content:"Traffic, rainfall and road conditions can change travel time. Use the Compass Map for saved locations and verify unfamiliar routes before depending on them for an important class or appointment.",category:"campus",audience:"all",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Preparing for a new academic week",summary:"A short weekly reset can reduce missed classes and last-minute academic stress.",content:"Review your timetable, upcoming events, deadlines and spending plan at the start of the week. Update any class venue or time changes you have verified.",category:"academic",audience:"students",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Avoiding misinformation",summary:"Treat unverified screenshots and forwarded messages carefully when they concern official university matters.",content:"Use official DELSU channels or the responsible university unit to verify institutional information. DELSU Compass community content is moderated but should not replace official confirmation for transactions or formal deadlines.",category:"general",audience:"all",status:"published",publishedBy:aid,publishedAt:now},
  {title:D+"Post-UTME information placeholder",summary:"Use this notice card to test time-sensitive admission updates without publishing invented dates or cut-off marks.",content:"Administrators should replace this demo item with verified current information and a source link before public deployment.",category:"admission",audience:"public",status:"draft",publishedBy:undefined},
 ]);
 await upsertMany(GuideArticleModel,[
  {title:D+"First week on campus",category:"new_students",excerpt:"A practical first-week checklist for finding your rhythm around DELSU and Abraka.",content:"Set up your profile, enter your timetable, enable reminders, explore verified map locations, review accommodation information and save the public Information Hub for changing notices.",sortOrder:1,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"How to inspect accommodation",category:"accommodation",excerpt:"Questions to ask and things to inspect before paying for a room or apartment.",content:"Inspect the room physically. Ask about water, electricity, security, flooding, access roads, total charges and tenancy conditions. Confirm who owns or manages the property before payment.",sortOrder:2,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Getting around Abraka",category:"campus_abraka",excerpt:"Build familiarity with your regular routes before you urgently need them.",content:"Use the Compass Map for verified saved locations and route guidance. Keep in mind that road conditions and access can change, especially during heavy rainfall.",sortOrder:3,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Managing a student budget",category:"general",excerpt:"A simple approach to monthly spending, savings and everyday expenses.",content:"Start with expected income, choose a realistic spending limit, set aside important academic and accommodation costs, then record daily spending so small expenses are visible.",sortOrder:4,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Academic organization",category:"academic",excerpt:"Use a weekly timetable and reminders to reduce avoidable missed classes.",content:"Enter each course with its venue and time. Add carry-over courses clearly, resolve clashes deliberately and use reminders for classes that are easy to miss.",sortOrder:5,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Using community intelligence responsibly",category:"about_delsu",excerpt:"Useful student knowledge is strongest when it is specific, current and moderated.",content:"Post practical information, avoid rumours, do not expose sensitive personal details and report content that is misleading or unsafe. Student submissions remain subject to moderation.",sortOrder:6,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Planning your first month",category:"new_students",excerpt:"Turn the first few weeks into a repeatable routine for classes, movement and spending.",content:"Set up your timetable, note important campus locations, keep a realistic monthly budget and review official notices frequently until your routine becomes stable.",sortOrder:7,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Before paying for accommodation",category:"accommodation",excerpt:"A simple payment-safety checklist for student housing decisions.",content:"Confirm the property, inspect it physically where possible, understand all charges, collect evidence of payment and avoid pressure to transfer money before basic details are verified.",sortOrder:8,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Preparing for examinations",category:"academic",excerpt:"Use organization rather than last-minute memory to track examination details.",content:"Verify the official timetable, identify venues early, plan transport and prepare permitted materials. Keep DELSU Compass entries synchronized with information you have verified.",sortOrder:9,isPublished:true,publishedBy:aid,publishedAt:now},
  {title:D+"Finding reliable campus information",category:"about_delsu",excerpt:"Know which information can be community-sourced and which should come from official channels.",content:"Student tips can help with food, housing and movement. Admissions, payments, registration, results and institutional deadlines should always be confirmed through official university channels.",sortOrder:10,isPublished:true,publishedBy:aid,publishedAt:now},
 ]);
 await upsertMany(CommunityPostModel,[
  {title:D+"Good reading spots around campus",body:"Try quieter study areas during off-peak periods and keep alternatives in mind when your usual location is busy.",category:"academics",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"What to check before renting",body:"Ask about water, electricity, flooding, total charges, security and who is legally receiving payment before committing.",category:"services",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Where to print assignments quickly",body:"Keep more than one printing option in mind near your regular lecture area so deadlines do not depend on one shop being open.",category:"campus_tip",area:"Campus",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Rainy season movement tip",body:"Leave extra time for movement when rainfall is heavy and avoid routes that are visibly waterlogged.",category:"transport",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Group study planning tip",body:"Agree on a meeting point and duration before everyone starts moving. It saves time and reduces repeated calls when lecture schedules are tight.",category:"academics",area:"Campus",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Keep a backup transport option",body:"If you depend on one route or pickup point, identify a second option for days when weather or traffic changes your usual movement plan.",category:"transport",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Inspect service charges before committing",body:"For student services, ask what the quoted price includes before work starts so you can compare options more fairly.",category:"services",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Simple food budgeting idea",body:"Set a realistic daily food range and record unusually expensive days. It helps you notice when small purchases are pushing the month off plan.",category:"food",area:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"New student campus tip",body:"Save the locations you will use most often during your first week so you are not searching for them under time pressure.",category:"campus_tip",area:"Campus",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Pending student food tip",body:"This entry intentionally remains pending so the administrator moderation queue can be tested.",category:"food",area:"Abraka",status:"pending",submittedBy:sid},
  {title:D+"Pending lost item notice",body:"Demo moderation item for testing how pending lost-and-found contributions appear in the admin console.",category:"lost_found",area:"Campus",status:"pending",submittedBy:sid},
 ]);
 await upsertMany(EventModel,[
  {title:D+"Tech Students Meetup",description:"A demo student technology meetup used to test event discovery, moderation cards and date presentation.",category:"club",startDate:future(3,15),endDate:future(3,17),venue:"Faculty of Computing area",organizer:"Demo Student Tech Community",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Career Development Workshop",description:"A practical career workshop demo covering CV preparation, portfolios and early-career planning.",category:"career",startDate:future(7,11),endDate:future(7,14),venue:"Campus seminar venue",organizer:"Demo Career Team",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Departmental Seminar",description:"A sample academic seminar item for testing upcoming event discovery and admin moderation.",category:"academic",startDate:future(10,10),venue:"Academic block",organizer:"Demo Department",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"CV and Portfolio Clinic",description:"Demo hands-on session where students review CV structure and portfolio presentation for internships and graduate roles.",category:"career",startDate:future(14,12),endDate:future(14,15),venue:"Campus training room",organizer:"Demo Career Community",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Student Entrepreneurship Session",description:"Demo entrepreneurship event for testing event cards, filters and upcoming-event dashboard integration.",category:"career",startDate:future(17,13),venue:"Campus seminar venue",organizer:"Demo Enterprise Network",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Campus Fitness Morning",description:"Demo social fitness event used to test date ordering and mobile event presentation.",category:"sports",startDate:future(5,7),venue:"Campus recreation area",organizer:"Demo Fitness Club",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Study Skills Session",description:"Demo academic support session about planning reading time and preparing for assessment periods.",category:"academic",startDate:future(20,10),venue:"Academic block",organizer:"Demo Study Group",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Pending Student Leadership Forum",description:"This demo event intentionally waits for admin approval so the moderation queue is populated.",category:"social",startDate:future(12,13),venue:"Campus venue",organizer:"Demo Student Group",status:"pending",submittedBy:sid},
 ]);
 await upsertMany(OpportunityModel,[
  {title:D+"Software Engineering Internship",description:"Demo internship opportunity for testing deadlines, search, cards and moderation.",type:"internship",provider:"Demo Technology Company",deadline:future(18),eligibility:"Students with basic web development knowledge.",location:"Remote / Nigeria",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Student Innovation Challenge",description:"Demo competition for students who want to test the opportunities discovery workflow.",type:"competition",provider:"Demo Innovation Hub",deadline:future(24),eligibility:"Open to student teams.",location:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Digital Skills Training",description:"Demo training opportunity covering practical digital skills for students.",type:"training",provider:"Demo Skills Network",deadline:future(15),eligibility:"Current students.",location:"Online",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Frontend Development Internship",description:"Demo internship listing for students building practical frontend development portfolios.",type:"internship",provider:"Demo Web Studio",deadline:future(28),eligibility:"Basic React or JavaScript knowledge.",location:"Hybrid / Nigeria",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Undergraduate Research Opportunity",description:"Demo research-support opportunity used to test opportunity filtering and deadline presentation.",type:"other",provider:"Demo Research Group",deadline:future(32),eligibility:"Interested undergraduate students.",location:"Campus",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Open Source Contributor Programme",description:"Demo programme for students interested in collaborating on public software projects.",type:"training",provider:"Demo Developer Community",deadline:future(35),eligibility:"Students willing to learn Git and collaborative workflows.",location:"Remote",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Student Community Grant",description:"Demo small-grant opportunity for testing grants in the discovery interface.",type:"grant",provider:"Demo Student Development Fund",deadline:future(40),eligibility:"Student-led community projects.",location:"Abraka",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Pending Volunteer Programme",description:"This item intentionally remains pending to test opportunity moderation.",type:"volunteering",provider:"Demo Community Project",deadline:future(20),eligibility:"Students available on weekends.",location:"Abraka",status:"pending",submittedBy:sid},
 ]);
 await upsertMany(AccommodationModel,[
  {title:D+"Self-contained apartment near campus",area:"Abraka",addressLandmark:"Near a major campus route",annualRent:420000,roomType:"self_contained",description:"Demo accommodation listing for testing approved cards, filters, rent summaries and detail views.",facilities:["Water","Fenced compound"],waterSupply:"good",electricity:"fair",security:"good",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Budget-friendly student room",area:"Abraka",addressLandmark:"Student residential area",annualRent:250000,roomType:"single_room",description:"Demo single-room listing. Distance is intentionally omitted to test optional distance handling.",facilities:["Water"],waterSupply:"fair",security:"fair",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"One-bedroom student apartment",area:"Abraka",addressLandmark:"Near a student residential route",annualRent:520000,roomType:"one_bedroom",description:"Demo one-bedroom listing for testing room-type filters and rent-range summaries.",facilities:["Water","Kitchen","Fenced compound"],distanceToCampusKm:2.4,waterSupply:"good",electricity:"fair",security:"good",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Shared two-bedroom apartment",area:"Abraka",addressLandmark:"Residential area close to student services",annualRent:360000,roomType:"shared_room",description:"Demo shared apartment listing suitable for testing comparison cards and optional facilities.",facilities:["Water","Wardrobe","Kitchen"],distanceToCampusKm:1.8,waterSupply:"good",electricity:"fair",security:"fair",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Student hostel room",area:"Abraka",addressLandmark:"Near a major student route",annualRent:210000,roomType:"hostel",description:"Demo hostel-style listing used to test lower rent ranges and accommodation search.",facilities:["Water","Shared compound"],waterSupply:"fair",electricity:"fair",security:"good",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Quiet self-contained room",area:"Abraka",addressLandmark:"Quieter residential area",annualRent:470000,roomType:"self_contained",description:"Demo listing for testing accommodation diversity and cards without requiring a distance value.",facilities:["Water","Private bathroom"],waterSupply:"good",electricity:"good",security:"good",imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"approved",submittedBy:sid,moderatedBy:aid,moderatedAt:now},
  {title:D+"Pending shared apartment",area:"Abraka",addressLandmark:"Near student housing area",annualRent:300000,roomType:"shared_room",description:"This demo accommodation entry remains pending so the admin queue can be tested.",facilities:["Water","Wardrobe"],imageUrls:[],contactName:"Demo Listing Contact",contactPhone:"08000000000",status:"pending",submittedBy:sid},
 ]);
 await upsertMany(SafetyAlertModel,[
  {title:D+"Use caution on poorly lit routes",description:"Demo safety information used to test public alert cards and filters.",category:"lighting",severity:"moderate",area:"Campus and nearby routes",safetyAdvice:"Prefer well-lit routes and move with others when appropriate.",status:"active",publishedBy:aid,publishedAt:now},
  {title:D+"Heavy rainfall movement advisory",description:"Demo weather-related movement advisory for testing the safety centre.",category:"road_hazard",severity:"low",area:"Abraka",safetyAdvice:"Avoid visibly flooded routes and allow extra travel time.",status:"active",publishedBy:aid,publishedAt:now},
  {title:D+"Secure personal belongings in crowded areas",description:"Demo awareness alert used to test additional safety categories and card density.",category:"security",severity:"moderate",area:"Busy campus areas",safetyAdvice:"Keep phones, wallets and bags secure and avoid leaving valuables unattended.",status:"active",publishedBy:aid,publishedAt:now},
  {title:D+"Report suspicious activity through the safety centre",description:"Demo safety information showing how reporting and public alerts are separate workflows.",category:"suspicious_activity",severity:"moderate",area:"Campus",safetyAdvice:"Use the in-app report for useful information, but contact the appropriate emergency or security service directly for urgent situations.",status:"active",publishedBy:aid,publishedAt:now},
  {title:D+"Take care around damaged road sections",description:"Demo road-hazard alert used to test filtering and severity presentation.",category:"road_hazard",severity:"moderate",area:"Abraka routes",safetyAdvice:"Reduce speed, use visible paths and avoid flooded or damaged sections where possible.",status:"active",publishedBy:aid,publishedAt:now},
 ]);
 await SafetyReportModel.findOneAndUpdate({description:D+"Pending report about a poorly lit route"},{$set:{category:"lighting",severity:"moderate",description:D+"Pending report about a poorly lit route",locationName:"Demo campus route",incidentAt:new Date(),status:"pending",allowAnonymousPublicUse:true,submittedBy:sid}},{upsert:true,new:true,setDefaultsOnInsert:true});
 await SafetyReportModel.findOneAndUpdate({description:D+"Pending report about a road obstruction"},{$set:{category:"road_hazard",severity:"low",description:D+"Pending report about a road obstruction",locationName:"Demo Abraka route",incidentAt:new Date(),status:"pending",allowAnonymousPublicUse:true,submittedBy:sid}},{upsert:true,new:true,setDefaultsOnInsert:true});
 await SafetyReportModel.findOneAndUpdate({description:D+"Reviewing suspicious activity report"},{$set:{category:"suspicious_activity",severity:"moderate",description:D+"Reviewing suspicious activity report",locationName:"Demo campus area",incidentAt:new Date(),status:"reviewing",allowAnonymousPublicUse:false,submittedBy:sid,reviewedBy:aid,reviewedAt:now}},{upsert:true,new:true,setDefaultsOnInsert:true});
 await LocationModel.findOneAndUpdate({name:D+"Faculty of Computing demo point"},{$set:{name:D+"Faculty of Computing demo point",description:"Demo map location for testing search and routing. Replace with an administrator-verified exact point before production.",category:"academic",area:"Abraka",campusSite:"Campus",latitude:5.79,longitude:6.1047,isActive:true,isVerified:true}},{upsert:true,new:true,setDefaultsOnInsert:true});
 console.log("Demo content seeded. All demo records are clearly labelled [DEMO].");
 console.log("Use npm run seed:demo:clear to remove demo content without deleting normal users/data.");
 await disconnectDatabase();
}
run().catch(async e=>{console.error(e);await disconnectDatabase().catch(()=>undefined);process.exit(1)});
