import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, ShieldCheck, UserRoundCheck, UserRoundX } from "lucide-react";
import { adminApi } from "./admin.api";

export function UserManagementPage(){
  const qc=useQueryClient(); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [verified,setVerified]=useState(""); const [page,setPage]=useState(1);
  const query=useQuery({queryKey:["admin","users",search,status,verified,page],queryFn:()=>adminApi.users({search:search||undefined,status:status||undefined,verified:verified||undefined,page,limit:20})});
  const toggle=useMutation({mutationFn:({id,isActive}:{id:string;isActive:boolean})=>adminApi.setUserStatus(id,isActive),onSuccess:()=>{void qc.invalidateQueries({queryKey:["admin","users"]});void qc.invalidateQueries({queryKey:["admin","overview"]})}});
  return <main className="p-5 md:p-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.22em] text-blue-700">Account administration</p><h1 className="mt-2 text-3xl font-black">Student accounts</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Search student accounts, check verification status and disable or restore accounts when moderation or security requires it. This page does not expose private student feature data.</p>
    <div className="mt-6 grid gap-3 rounded-3xl border border-blue-100 bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-500"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, email, faculty or department" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:bg-white"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">All account states</option><option value="active">Active</option><option value="disabled">Disabled</option></select><select value={verified} onChange={e=>{setVerified(e.target.value);setPage(1)}} className="rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">All verification</option><option value="true">Verified</option><option value="false">Unverified</option></select></div>
    {query.isError&&<div className="mt-4 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{(query.error as any)?.response?.data?.error?.message??"Student accounts could not be loaded."}</div>}
    <div className="mt-4 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><p className="text-sm font-black">{query.data?.total??0} student accounts</p><p className="text-xs text-slate-500">Page {query.data?.page??page} of {query.data?.pages??1}</p></div>{query.isLoading?<div className="p-10 text-center text-sm text-slate-500">Loading student accounts…</div>:query.data?.items.length?<div className="divide-y divide-slate-100">{query.data.items.map(s=><article key={s.id} className="grid gap-4 p-5 lg:grid-cols-[1.3fr_1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{s.fullName}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${s.isVerified?"bg-blue-50 text-blue-700":"bg-amber-50 text-amber-700"}`}>{s.isVerified?"verified":"unverified"}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${s.isActive?"bg-sky-50 text-sky-700":"bg-red-50 text-red-700"}`}>{s.isActive?"active":"disabled"}</span></div><p className="mt-1 text-sm text-slate-600">{s.email}</p></div><div className="text-sm text-slate-600"><p>{s.faculty||"Faculty not set"}</p><p className="mt-1 text-xs text-slate-500">{s.department||"Department not set"}{s.level?` · ${s.level} Level`:""}</p></div><button disabled={toggle.isPending} onClick={()=>{const action=s.isActive?"disable":"restore";if(window.confirm(`${action[0].toUpperCase()+action.slice(1)} ${s.fullName}'s account?`))toggle.mutate({id:s.id,isActive:!s.isActive})}} className={`inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-black ${s.isActive?"border border-red-200 bg-red-50 text-red-700":"bg-blue-700 text-white"}`}>{s.isActive?<UserRoundX className="h-4 w-4"/>:<UserRoundCheck className="h-4 w-4"/>}{s.isActive?"Disable":"Restore"}</button></article>)}</div>:<div className="p-10 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-bold text-slate-500">No student accounts match these filters.</p></div>}</div>
    <div className="mt-4 flex justify-end gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-black disabled:opacity-30">Previous</button><button disabled={page>=(query.data?.pages??1)} onClick={()=>setPage(p=>p+1)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-black disabled:opacity-30">Next</button></div>
  </div></main>
}
