import type { RequestHandler } from "express";
import { accommodationService } from "./accommodation.service.js";
import { accommodationAdminService } from "./accommodation-admin.service.js";
export const listPublic: RequestHandler = async (req,res,next)=>{try{res.json({success:true,data:await accommodationService.listPublic(req.query)})}catch(e){next(e)}};
export const getPublic: RequestHandler = async (req,res,next)=>{try{res.json({success:true,data:await accommodationService.getPublic(String(req.params.id))})}catch(e){next(e)}};
export const listMine: RequestHandler = async (req,res,next)=>{try{res.json({success:true,data:await accommodationService.listMine(req.auth!.userId)})}catch(e){next(e)}};
export const createListing: RequestHandler = async (req,res,next)=>{try{res.status(201).json({success:true,message:"Accommodation submitted for moderation",data:await accommodationService.create(req.auth!.userId,req.body)})}catch(e){next(e)}};
export const updateListing: RequestHandler = async (req,res,next)=>{try{res.json({success:true,message:"Listing updated and returned to moderation",data:await accommodationService.updateMine(req.auth!.userId,String(req.params.id),req.body)})}catch(e){next(e)}};
export const deleteListing: RequestHandler = async (req,res,next)=>{try{await accommodationService.removeMine(req.auth!.userId,String(req.params.id));res.json({success:true,message:"Listing deleted"})}catch(e){next(e)}};
export const createReview: RequestHandler = async (req,res,next)=>{try{res.status(201).json({success:true,message:"Review submitted for moderation",data:await accommodationService.createReview(req.auth!.userId,String(req.params.id),req.body)})}catch(e){next(e)}};
export const reportListing: RequestHandler = async (req,res,next)=>{try{res.status(201).json({success:true,message:"Report submitted",data:await accommodationService.report(req.auth!.userId,String(req.params.id),req.body)})}catch(e){next(e)}};
export const adminCreateListing: RequestHandler=async(req,res,next)=>{try{res.status(201).json({success:true,message:"Accommodation published",data:await accommodationAdminService.createListing(req.auth!.userId,req.body)})}catch(e){next(e)}};
export const adminListings: RequestHandler=async(req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.listings((typeof req.query.status === "string" ? req.query.status : undefined))})}catch(e){next(e)}};
export const moderateListing: RequestHandler=async(req,res,next)=>{try{res.json({success:true,message:"Listing moderation updated",data:await accommodationAdminService.moderateListing(req.auth!.userId,String(req.params.id),req.body.status,req.body.reason)})}catch(e){next(e)}};
export const adminReviews: RequestHandler=async(req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.reviews((typeof req.query.status === "string" ? req.query.status : undefined))})}catch(e){next(e)}};
export const moderateReview: RequestHandler=async(req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.moderateReview(req.auth!.userId,String(req.params.id),req.body.status)})}catch(e){next(e)}};
export const adminReports: RequestHandler=async(req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.reports((typeof req.query.status === "string" ? req.query.status : undefined))})}catch(e){next(e)}};
export const resolveReport: RequestHandler=async(req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.resolveReport(req.auth!.userId,String(req.params.id),req.body.status,req.body.resolutionNote)})}catch(e){next(e)}};
export const adminStats: RequestHandler=async(_req,res,next)=>{try{res.json({success:true,data:await accommodationAdminService.stats()})}catch(e){next(e)}};
